### ISSUE TITLE
Flathub showing wrong version

### ISSUE THREAD

**Issue by Findarato** [flathub/com.getmailspring.Mailspring#10]
I am not sure if this is the correct location to post this or not.  Flathub is showing version 1.9.2

**Comment by prateekmedia** [comment]
You are right...

You posted in wrong repository, although we can tweak this but it's better to modify below file and add versions in that.

https://github.com/Foundry376/Mailspring/blob/b2e69c4b0ab77c07b2561eda62ec725969957803/app/build/resources/linux/mailspring.appdata.xml.in#L36

**Comment by prateekmedia** [comment]
If you are interested you can create a PR to add the newer versions in the above mentioned file.

**Comment by matheusreich** [comment]
As seen above, I've applied the necessary changes to the necessary file on https://github.com/Foundry376/Mailspring/blob/c3dec44ef4e37dc04633a093e1039affe0ffb743/app/build/resources/linux/mailspring.appdata.xml.in, which should now get Flathub to display the correct version of Mailspring.

**Comment by khewweifeng** [comment]
Hi, Flathub still showing version 1.9.2 

![image](https://user-images.githubusercontent.com/54496743/205432452-b4c45573-e844-4bad-b573-981ed8995e44.png)

https://flathub.org/apps/details/com.getmailspring.Mailspring
