### ISSUE TITLE
Security problem

### ISSUE THREAD

**Issue by vroger11** [flathub/com.getmailspring.Mailspring#13]
Just after first install I get the following message:
"Mailspring could not store your password securely. Make sure you have libsecret installed and a keyring is present."
Maybe a dependence is missing on this flatpak.

Note: I use manjaro kde and libsecret is installed on my system

**Comment by Drsheppard01** [comment]
Needed kde-wallet or gnome-keyring package

**Comment by vroger11** [comment]
I have both installed on my system (not as flatpak). Maybe some permissions are needed from the mailspring flapak

**Comment by marco-calautti** [comment]
I also have the same issue. Gnome-keyring and kde-wallet are both installed on my system, but on first run, Mailspring shows me the same error.

**Comment by prateekmedia** [comment]
Also happened to me in Fedora but I don't know a solution.

**Comment by ademlabs** [comment]
Still happening as of now. I would say this should be reopened for closer inspection.
