### ISSUE TITLE
libsecret or gnome-keyring not found error, though both libsecret and gnome-keyring are installed in host

### ISSUE THREAD

**Issue by shakeelansari63** [flathub/com.getmailspring.Mailspring#17]
Hello,

I installed the mailspring from Flatpak and it is not allowing me to logon to any of my mail account and throws libsecret not found error. 
I checked and I have libsecret and gnome-keyring package installed on my host system.

**Error Message -** 
![image](https://user-images.githubusercontent.com/8319053/189519209-8a91f6ea-b06a-479f-a0b7-45ee4eb18c05.png)

**System -** 
Fedora 36

**Flatpak Version -** 
![image](https://user-images.githubusercontent.com/8319053/189519231-e54a6e99-04e2-49c0-9cd6-68f0974966d8.png)

**Gnome Keyring Installed -** 
![image](https://user-images.githubusercontent.com/8319053/189519303-d088a2d5-c35b-4219-901c-30d39fa14ffc.png)

**Comment by prateekmedia** [comment]
@hfiguiere Any idea why this is coming? It also happened to me once before.

**Comment by shakeelansari63** [comment]
This is an old issue on libsecret but still Open. It says that some D-BUS API changes in libsecret 0.20 could be culprit. Not Sure if that is still the case. 

https://gitlab.gnome.org/GNOME/libsecret/-/issues/49

**Comment by shakeelansari63** [comment]
Hello Developers, Is anybody looking into this?

**Comment by peterlobster** [comment]
I had this issue as well. I really wanted to try MailSpring, but have ended up using Evolution that currently works.

---

(FMU)

The libsecret dependency issue I believe would be handled through the FlatPak's Runtime and SDK, which are currently set to...
```yml
runtime: org.freedesktop.Platform
sdk: org.freedesktop.Sdk
```
If you look closely at the that docs, you'll see that [the documentation specifies that this Runtime and SDK](https://docs.flatpak.org/en/latest/available-runtimes.html#freedesktop) only provides "a set of essential libraries and services..." in which libsecret is not specified. However, if you're look at [the GNOME Runtime and SDK documented in that page](https://docs.flatpak.org/en/latest/available-runtimes.html#gnome)  you'll see the `Libsecret` is specified as a provided resource.

So I think this is simply a matter of the wrong Runtime / SDK.

**Comment by csc-chicken** [comment]
@peterlobster  Oh !! No wonder mailspring stop working after update. We have to wait sdk to upgrade
