### ISSUE TITLE
FlatPak update

### ISSUE THREAD

**Issue by hunnsdon** [flathub/com.getmailspring.Mailspring#23]
Is there a FlatPak update for the latest Mailspring release?

Currently there is a nag to update, although this takes you to the site download.

![Screenshot from 2023-02-24 09-58-10](https://user-images.githubusercontent.com/24774509/221150337-d3df316d-3d47-49f1-ba80-cb48d4260997.png)

**Comment by jakobkmar** [comment]
See also #22, #21 and https://github.com/Foundry376/Mailspring/pull/2442 for a possible fix.

**Comment by marc0x1** [comment]
Is it unmaintained?

**Comment by hunnsdon** [comment]
> Is it unmaintained?

I don't know, I have given up with the FlatPak version. I have gone over to the [.deb](https://updates.getmailspring.com/download?platform=linuxDeb) download from Mailspring website.

My repository still is at 1.10.7
